{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/CallError\/Shutdown"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Shutdown"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore","doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/CallError"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"symbolKind":"case","externalID":"s:18LiveViewNativeCore9CallErrorO8ShutdownyA2CmF","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Shutdown"}],"title":"CallError.Shutdown","modules":[{"name":"LiveViewNativeCore"}]},"abstract":[{"text":"The async task for the [Channel] was already joined by another call, so the [Result] or","type":"text"},{"text":" ","type":"text"},{"text":"panic from the async task can’t be reported here.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/liveviewnativecore\/callerror\/shutdown"]}],"sections":[],"references":{"doc://liveview-native-core.LiveViewNativeCore/documentation/LiveViewNativeCore":{"title":"LiveViewNativeCore","kind":"symbol","url":"\/documentation\/liveviewnativecore","type":"topic","role":"collection","identifier":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore","abstract":[]},"doc://liveview-native-core.LiveViewNativeCore/documentation/LiveViewNativeCore/CallError":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallError"}],"url":"\/documentation\/liveviewnativecore\/callerror","role":"symbol","title":"CallError","type":"topic","abstract":[{"text":"Errors when calling [Channel::call].","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallError","kind":"identifier"}],"identifier":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/CallError"},"doc://liveview-native-core.LiveViewNativeCore/documentation/LiveViewNativeCore/CallError/Shutdown":{"identifier":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/CallError\/Shutdown","abstract":[{"type":"text","text":"The async task for the [Channel] was already joined by another call, so the [Result] or"},{"text":" ","type":"text"},{"text":"panic from the async task can’t be reported here.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"Shutdown","kind":"identifier"}],"type":"topic","url":"\/documentation\/liveviewnativecore\/callerror\/shutdown","title":"CallError.Shutdown","role":"symbol"}}}